name: Frontend CI

on:
  push:
    paths:
      - "client-wpf/**"
      - ".github/workflows/frontend-ci.yml"
  pull_request:
    paths:
      - "client-wpf/**"
      - ".github/workflows/frontend-ci.yml"

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore client-wpf/AIMD.ReportApp.sln

      - name: Build
        run: dotnet build client-wpf/AIMD.ReportApp.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test client-wpf/AIMD.ReportApp.sln --configuration Release --no-build
